on: [workflow_dispatch, push]
name: Build & Test Multiarch Containers
jobs:
    test:
      runs-on: ubuntu-latest
      if: ${{ !contains(github.event.head_commit.message, '[no ci]') }}
      steps:
        - uses: actions/checkout@v3
        - uses: redhat-actions/buildah-build@main
          with:
            image: multiarch
            tags: latest
            containerfiles: |
              ./Containerfile
        - run: |
            echo "Running image"
            podman run --rm multiarch:latest
        - uses: actions/github-script@v6
          id: fail-test
          with:
            script: core.setFailed('Try to fail a job')
    build:
      runs-on: ubuntu-latest
      if: ${{ !contains(github.event.head_commit.message, '[no ci]') }}
      needs: test
      steps:
        - uses: actions/checkout@v3
        - run: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
        - uses: redhat-actions/buildah-build@main
          with:
            image: multiarch
            tags: latest
            archs: amd64, arm64
            containerfiles: |
              ./Containerfile
        - run: |
            echo "Built images: "
            buildah images